### ISSUE TITLE
Error : Merging functional information returns empty object

### ISSUE THREAD

**Issue by Prakrithi-P** [dcalderon/rolypoly#11]
Dear Author,
I have used rolyPoly before and has worked fine. Now I am trying to identify novel transcripts that are relevant to a trait, and hence have different IDs and not ENS gene IDs (anno_rp image attached). I don't know if this is the problem, whether rolyPoly is meant to analyze only genes. I get an error where after merging functional information, an empty object is returned (image attached). All the other file formats are fine, the reference builds match and the chromosome IDs  match. Can you please help me with this?

![error_rp](https://user-images.githubusercontent.com/70966155/168087652-62713b15-dd60-40ae-9bf6-0d6036743afd.png)
![anno_rp](https://user-images.githubusercontent.com/70966155/168087676-15851a82-15c9-4d7b-afde-66206c841a11.png)

Thanks,
Prakrithi

**Comment by dcalderon** [comment]
Hello,

Just a guess at this point, but would this work if you changed the
chromosome naming scheme from '1' -> 'chr1'. This might be affecting the LD
lookup.

Best,
Diego

**Comment by Prakrithi-P** [comment]
Hi Diego,
Thank you for the response. The chromosome naming is maintained uniform
throughout. It's'1', '2',... in the LD files, GWAS and block annotations.
Still doesn't work. Even if I add chr it throws an error 'remove chr from
chrom and rerun'.

**Comment by dcalderon** [comment]
Sorry that last suggestion wasn't helpful. I'm not exactly sure what the issue is. But, the code should run fine with arbitrary blocks (they do not necessarily have to be genes).

Do you have a sample of the GWAS you're trying to use with this? The 'chr1 missing' message is an indication that it's not being found in the GWAS. So maybe these block regions aren't linking up with the GWAS correctly and then it's returning empty.

**Comment by dcalderon** [comment]
For now I'll close this issue since I haven't heard back, but feel free to re-open if the last message didn't solve the issue.
